site_name: sanic-dantic

theme:
  name: 'material'
  icon:
    logo: material/api
  font:
    code: Roboto Mono
  language: en
  palette:
    scheme: default
    primary: indigo
    accent: light blue
  features:
    - toc.integrate

nav:
  - Overview: index.md
  - Installation: 02_Installation.md
  - Usage:
      - SimpleUsage: 03_SimpleUsage.md
      - FunctionBasedViewUsage: 04_FunctionBasedViewUsage.md
      - ClassBasedViewUsage: 05_ClassBasedViewUsage.md
  - Attention: 06_Attention.md
  - API Reference: 07_APIReference.md
  - Todo List: 08_TodoList.md
  - Thanks: 09_Thanks.md
  - License: 10_License.md

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: true
repo_url: https://github.com/miss85246/sanic-dantic/
repo_name: sanic-dantic
copyright: Copyright &copy; 2020 Connor Zhang