site_name: sanic-dantic

theme:
  name: 'material'
  palette:
    primary: deep orange
    accent: deep orange

nav:
  - Overview: Index.md
  - Installation: Installation.md
  - Usage:
      - SimpleUsage: SimpleUsage.md
      - FunctionBasedViewUsage: FunctionBasedViewUsage.md
      - ClassBasedViewUsage: ClassBasedViewUsage.md
  - Attention: Attention.md
  - Pydantic: Pydantic.md
  - Thanks: Thanks.md
  - License: License.md

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/miss85246/sanic-dantic

copyright: Copyright &copy; 2020 Connor Zhang